version: '3.3'

services:

  bb-db:
    image: ${dockerId:-dockersamples}/lunch-and-learn-db:v5
    build:
      context: ./lunch-and-learn-db
    networks:
      - bb-net

  bb-app:
    image: ${dockerId:-dockersamples}/lunch-and-learn-app:v5
    build:
      context: ./lunch-and-learn-app
    depends_on:
      - bb-db
    restart: on-failure
    networks:
      - bb-net

networks:
  bb-net:
