version: '3.3'

services:

  bb-db:
    image: ${dockerId:-dockersamples}/lunch-and-learn-db:v5
    build:
      context: ./lunch-and-learn-db
    networks:
      - bb-net

  bb-app:
    image: ${dockerId:-dockersamples}/lunch-and-learn-app:v5
    build:
      context: ./lunch-and-learn-app
    depends_on:
      - bb-db
    restart: on-failure
    networks:
      - bb-net

  bb-proxy:
    image: ${dockerId:-dockersamples}/lunch-and-learn-proxy:v5
    build:
      context: ./lunch-and-learn-proxy
    ports:
      - "80:80"
    depends_on:
      - bb-app
    networks:
      - bb-net

  bb-metrics:
    image: ${dockerId:-dockersamples}/lunch-and-learn-metrics:v5
    build:
      context: ./lunch-and-learn-metrics
    depends_on:
      - bb-app
    networks:
      - bb-net

  bb-dashboard:
    image: ${dockerId:-dockersamples}/lunch-and-learn-dashboard:v5
    build:
      context: ./lunch-and-learn-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - bb-metrics
    networks:
      - bb-net

networks:
  bb-net:
